---
title: "Data prep for IGFS Shiny App"
output:
  html_document:
    toc: true
    theme: united
date: '`r format(Sys.time(), "%d %B, %Y")`'
author: Olga Kalinina # change name 
---

```{r include=FALSE}
library(knitr)
library(RODBC)
library(dplyr)
library(reshape2)
library(tidyr)
```

## Pulling Data from Informatics load(except NEP)



```{r pulling data}


channel <- odbcDriverConnect("Driver=SQL Server; 
                             Server=XXXX; Database=InformaticsLoad")

########Get Data from Informatics Load######

data1<- sqlQuery(channel,"
SELECT *
FROM [InformaticsLoad].[dbo].[SurveyAbundanceAndDistribution]
")

summary(data1)
str(data1)


dat<- sqlQuery(channel,"
SELECT *
FROM [InformaticsLoad].[dbo].[SurveyCatchRate]
")

summary(dat)
str(dat)



LengthData<- sqlQuery(channel,"
SELECT *
FROM [InformaticsLoad].[dbo].[SurveyLenghtData]
")

summary(LengthData)
str(LengthData)

LengthWeightAge<- sqlQuery(channel,"
SELECT *
FROM [InformaticsLoad].[dbo].[SurveyLenghtWeightAge]
")
summary(LengthWeightAge)
str(LengthWeightAge)

stn<- sqlQuery(channel,"
SELECT *
FROM [InformaticsLoad].[dbo].[SurveyMI_Survey_Station_Data]
WHERE fldcruisename like 'IGFS%'
")

summary(stn)
str(stn)

saveRDS(stn,"updatedData/stn.RDS")

close(channel)

```




## Getting ready NEP data

```{r NEP data}
nep<-read.csv("gfs_nep_final_IBTS.csv")#.csv from L:\Surveys\IGFS\Nephrops
summary(nep)

#join with stn data

stnNep<-stn%>%select( "fldCruiseName" ,"fldCruiseStationNumber", "fldShotLatDecimalDegrees" ,"fldShotLonDecimalDegrees",
                    "fldHaulLatDecimalDegrees","fldHaulLonDecimalDegrees" ,"Gear_Type", "TowDurationMin"  ,"AreaKmSq"  )

names(nep)[c(8,9)]<-c("fldCruiseName"   ,         "fldCruiseStationNumber")
datN<-merge(nep, stnNep, by.x=c("fldCruiseName"   ,"fldCruiseStationNumber"))
datN<-datN[c(3:9,1,2,10:21)]
names(datN)[c(8,9,21)]<-c("Survey_Code","Haul","AreaKmSq")
summary(datN)
```


##Prep data and save in folder updatedData

### Main Page Data

```{r Main Page Data}


##################################Main Pagedata######################################################


# ###############For SpAggdata################
 dd<-data1%>% group_by(fldPrimeStation,Yr,LonDec,LatDec,Species)%>%summarise(CatchKg=sum(CatchKg))
 d0<-data1%>% group_by(fldPrimeStation,Yr,LonDec,LatDec)%>%summarise(CatchKg=sum(CatchKg))
 
 
 SpAggdata<- dcast(dd, fldPrimeStation +Yr+LonDec+LatDec ~ Species, value.var="CatchKg")
 SpAggdata$CatchKg<-d0$CatchKg
 

###################################################
#######################For mapdata###########################

 mapdata<-aggregate(data1[,c("AreaKmSq","CatchKg", "RaisedNo")], 
                            by=list(data1$fldPrimeStation,data1$LonDec, data1$LatDec,data1$Yr),FUN=sum,  na.rm=TRUE)
 names(mapdata) = c("PrimeStation", "Longitude"  ,  "Latitude"   ,  "Year"   ,      "AreaKmSq" , 
                            "CatchKg"    ,  "RaisedNo")
 
 saveRDS(mapdata,"updatedData/mapdata.RDS")

##################################################
################sp_data_gr########################




 temp<-aggregate(data1[,c("AreaKmSq","CatchKg", "RaisedNo")], 
                 by=list(data1$fldPrimeStation,data1$LonDec, data1$LatDec,data1$Yr,data1$Species),FUN=sum,  na.rm=TRUE)
 names(temp) = c("PrimeStation", "Longitude"  ,  "Latitude"   ,  "Year"   ,  "Species" ,    "AreaKmSq" , 
                 "CatchKg"    ,  "RaisedNo")
 
 temp$Group<-temp$Species
 
 levels(temp$Group)[which(levels(temp$Group) %in% c("ARG", "BOF", "GSS", "HER" ,"HOM", "MAC", "SPR", "WHB"))]<-"Small pelagic" 
 levels(temp$Group)[which(levels(temp$Group) %in% c("BLR" ,"CUR", "DFL", "DGS" ,"DII" ,"LSD", "PTR", "SAR", "SDR" ,"SHR", "SKT" ,"THR", "UNR"))]<-"Elasmobranch" 
 levels(temp$Group)[which(levels(temp$Group) %in% c("COD", "ESB" ,"GUG", "HAD" ,"HKE", "JOD", "POK", "POL", "WHG"))]<-"Large demersal" 
 levels(temp$Group)[which(levels(temp$Group) %in% c("DAB", "LBI", "MEG", "PLE", "SOL"))]<-"Flat fish" 
 levels(temp$Group)[which(levels(temp$Group) %in% c("MON" ,"WAF"))]<-"Monkfish" 
 levels(temp$Group)[which(levels(temp$Group) %in% c("NOP", "POD"))]<-"Small demersal" 
 sp_data_gp<-temp

saveRDS(sp_data_gp,"updatedData/sp_data_gp.RDS")


```


### Species Data

```{r Species Data}



#Length/Weight and Length/Age plots

LengthWeightAge<-filter(LengthWeightAge,ICESCODE !="VIIa")
LengthWeightAge<-droplevels(LengthWeightAge[which(LengthWeightAge$fldMainSpeciesCode %in% levels(data1$Species)),])
LengthWeightAge<-filter(LengthWeightAge,fldGearDescription!="Griffin 43/53 - New IBTS prototype 2019 full size clean gear")
LengthWeightAge<-droplevels(LengthWeightAge)

#Used for Length Frequency and Total/Adults/Juvenile numbers

LengthData<-droplevels(LengthData[which(LengthData$Species %in% levels(data1$Species)),])
LengthData<-filter(LengthData,fldGearDescription!="Griffin 43/53 - New IBTS prototype 2019 full size clean gear")
LengthData<-droplevels(LengthData)
LengthData$CatchNos30minHaul=LengthData$CatchNos/LengthData$fldTowDuration*30

dat<-droplevels(dat[which(dat$Species %in% levels(data1$Species)),])
dat$symbSize <- sqrt( dat$Kg_Per_Hr/ pi )
dat$Year = as.numeric(substr(dat$Cruise,5,8))

 
dat1<-aggregate(dat[,c("Catch_Kg", "Kg_Per_Hr")], 
                 by=list(dat$Year,dat$Cruise, dat$Haul, dat$Prime_Stn, dat$Lon, dat$Lat, dat$Species),FUN=sum,  na.rm=TRUE)
names(dat1) = c("Year", "Cruise", "Haul", "Prime_Stn", "Lon", "Lat","Species", "Catch_Kg", "Kg_Per_Hr")
dat1$symbSize <- sqrt( dat1$Kg_Per_Hr/ pi )




#Used for CPUE


#Used for Distribution no/km2 and Abundance
Kg_Per_Hr<-with(data1,(data1$CatchKg/data1$Time_Min)*60)
##calculating swept area estimates
catch_km2<-with(data1,(1/AreaKmSq*CatchKg))
No_km2<-with(data1,(1/AreaKmSq*RaisedNo))
Area<-ifelse(data1$ICESCODE=="VIa","VI","VII")
data1<-cbind(data1,catch_km2,No_km2, Area,Kg_Per_Hr)
#Agregate by Haul and species to get unique haul data for skt
mapdataS<-aggregate(data1[,c("CatchKg", "RaisedNo", "catch_km2", "No_km2")], 
                   by=list(data1$Yr,data1$Haul,data1$LonDec, data1$LatDec, data1$Species),FUN=sum,  na.rm=TRUE)
names(mapdataS) = c("Year", "Haul", "LonDec", "LatDec","Species", "CatchKg", "RaisedNo", "catch_km2", "No_km2")
mapdataS$symbSize <- sqrt( mapdataS$No_km2/ pi )


#Total Numbers


#Total Numbers
if(dim(LengthData)[1]>0){
  TotalNumbersMap=aggregate(LengthData[,c("CatchNos", "CatchNos30minHaul")],
                            by=list(LengthData$Year,LengthData$fldCruiseStationNumber,
                                    LengthData$fldShotLonDecimalDegrees, LengthData$fldShotLatDecimalDegrees
                                    ,LengthData$Species),
                            FUN=sum,  na.rm=TRUE)
  names(TotalNumbersMap) = c("Year", "Haul", "LonDec", "LatDec","Species" ,"CatchNos", "CatchNos30minHaul")
  TotalNumbersMap$symbSize <- sqrt( TotalNumbersMap$CatchNos30minHaul/ pi )
}else{
  TotalNumbersMap=data.frame("Year"=maxyear,
                             "Haul"=NA,
                             "LonDec"=-9.558,
                             "LatDec"=55.109,
                             "Species"=NA,
                             "CatchNos"=NA,
                             "CatchNos30minHaul"=NA,
                             "symbSize"=NA)}

#Juveniles
Juveniles= filter(LengthData, AgeClassification=="Juvenile")
if(dim(Juveniles)[1]>0){
  JuvNumbersMap=aggregate(Juveniles[,c("CatchNos", "CatchNos30minHaul")],
                          by=list(Juveniles$Year,Juveniles$fldCruiseStationNumber,
                                  Juveniles$fldShotLonDecimalDegrees, Juveniles$fldShotLatDecimalDegrees,
                                  Juveniles$Species),
                          FUN=sum,  na.rm=TRUE)
  names(JuvNumbersMap) = c("Year", "Haul", "LonDec", "LatDec","Species", "CatchNos", "CatchNos30minHaul")
  JuvNumbersMap$symbSize <- sqrt( JuvNumbersMap$CatchNos30minHaul/ pi )
}else{
  JuvNumbersMap=data.frame("Year"=maxyear,
                           "Haul"=NA,
                           "LonDec"=-9.558,
                           "LatDec"=55.109,
                           "Species"=NA,
                           "CatchNos"=NA,
                           "CatchNos30minHaul"=NA,
                           "symbSize"=NA)}

#Adults
Adults= filter(LengthData, AgeClassification=="Adult")
if(dim(Adults)[1]>0){
  AdultNumbersMap=aggregate(Adults[,c("CatchNos", "CatchNos30minHaul")],
                            by=list(Adults$Year,Adults$fldCruiseStationNumber,
                                    Adults$fldShotLonDecimalDegrees, Adults$fldShotLatDecimalDegrees,
                                    Adults$Species),
                            FUN=sum,  na.rm=TRUE)
  names(AdultNumbersMap) = c("Year", "Haul", "LonDec", "LatDec","Species", "CatchNos", "CatchNos30minHaul")
  AdultNumbersMap$symbSize <- sqrt( AdultNumbersMap$CatchNos30minHaul/ pi )
}else{
  AdultNumbersMap=data.frame("Year"=maxyear,
                             "Haul"=NA,
                             "LonDec"=-9.558,
                             "LatDec"=55.109,
                             "Species"=NA,
                             "CatchNos"=NA,
                             "CatchNos30minHaul"=NA,
                             "symbSize"=NA)}
saveRDS(data1,"updatedData/data1.RDS")
saveRDS(dat,"updatedData/dat.RDS")
saveRDS(dat1,"updatedData/dat1.RDS")
saveRDS(LengthWeightAge,"updatedData/LengthWeightAge.RDS")
saveRDS(LengthData,"updatedData/LengthData.RDS")
saveRDS(mapdataS,"updatedData/mapdataS.RDS")
saveRDS(TotalNumbersMap,"updatedData/TotalNumbersMap.RDS")
saveRDS(AdultNumbersMap,"updatedData/AdultNumbersMap.RDS")
saveRDS(JuvNumbersMap,"updatedData/JuvNumbersMap.RDS")

```

### Nephrops Data
```{r Nephrops Data}
 datN$Functional_Unit<-as.factor(datN$Functional_Unit)
 datN<-filter(datN,Functional_Unit==16|Functional_Unit==17|Functional_Unit==19|Functional_Unit==22|Functional_Unit==99|Functional_Unit==2021)
 datN$Functional_Unit<-droplevels(datN$Functional_Unit)
 levels(datN$Functional_Unit)<-c("16" ,  "17" ,  "19" ,  "22" ,  "Outside FU" ,  "20-21")

 datN$Kg_Hr= datN$PredWt_Kg/datN$TowDurationMin*60
 datN$No_Km2= datN$NepCount/datN$AreaKmSq
 datN$No_30min = datN$NepCount/datN$TowDurationMin*30
 datN$AgeClassification<-datN$CLmm
 
 datN$AgeClassification[which(datN$CLmm>17)]<-"Adult"
 datN$AgeClassification[which(datN$CLmm<=17)]<-"Juvenile"
 datN$AgeClassification<-as.factor(datN$AgeClassification)
 datN$Functional_Unit<-as.factor(datN$Functional_Unit)

 dat_raised= aggregate(datN[,c("NepCount", "PredWt_Kg", "Kg_Hr", "No_Km2", "No_30min")], 
                       by=list(datN$Year, datN$Survey_Code, datN$Haul, datN$Functional_Unit, datN$Fishing_Grounds,
                               datN$fldShotLatDecimalDegrees,datN$fldShotLonDecimalDegrees, 
                               datN$fldHaulLatDecimalDegrees, datN$fldHaulLonDecimalDegrees,datN$Sex),
                      FUN=sum,  na.rm=TRUE)
names(dat_raised) = c("Year", "Survey_Code", "Haul", "Functional_Unit", "Fishing_Grounds",
                      "Lat", "Lon", "LatV2", "LonV2","Sex", "NepCount", "PredWt_Kg", "Kg_Hr", "No_Km2", "No_30min")
 
dat_raised$symbSize <- sqrt( dat_raised$Kg_Hr/ pi )
dat_raised$symbSize2 <- sqrt( dat_raised$No_Km2/ pi )
dat_raised$symbSize3 <- sqrt( dat_raised$No_30min/ pi )
 

 
 #Juveniles Nep
JuvenilesN= filter(datN, AgeClassification=="Juvenile")
if(dim(JuvenilesN)[1]>0){
 JuvNumbersMapN=aggregate(JuvenilesN[,c("NepCount", "PredWt_Kg", "Kg_Hr", "No_Km2", "No_30min")],
                          by=list(JuvenilesN$Year, JuvenilesN$Survey_Code, JuvenilesN$Haul, JuvenilesN$Functional_Unit, JuvenilesN$Fishing_Grounds,
                                  JuvenilesN$fldShotLatDecimalDegrees,JuvenilesN$fldShotLonDecimalDegrees, 
                                  JuvenilesN$fldHaulLatDecimalDegrees, JuvenilesN$fldHaulLonDecimalDegrees),
                           FUN=sum,  na.rm=TRUE)
 names(JuvNumbersMapN) = c("Year", "Survey_Code", "Haul", "Functional_Unit", "Fishing_Grounds",
                            "Lat", "Lon", "LatV2", "LonV2", "NepCount", "PredWt_Kg", "Kg_Hr", "No_Km2", "No_30min")
  JuvNumbersMapN$symbSize <- sqrt( JuvNumbersMapN$No_30min/ pi )
}else{
  JuvNumbersMapN=data.frame("Year"=maxyear, "Survey_Code"=NA, "Haul"=NA, "Functional_Unit"=NA, "Fishing_Grounds"=NA,
                             "Lat"=55.109, "Lon"=-9.558, "LatV2"=NA, "LonV2"=NA, "NepCount"=NA, "PredWt_Kg"=NA, 
                            "Kg_Hr"=NA, "No_Km2"=NA, "No_30min"=NA,"symbSize"=NA)}


 
# #Adults
 AdultsN= filter(datN, AgeClassification=="Adult")
 if(dim(AdultsN)[1]>0){
  AdultNumbersMapN=aggregate(AdultsN[,c("NepCount", "PredWt_Kg", "Kg_Hr", "No_Km2", "No_30min")],
                             by=list(AdultsN$Year, AdultsN$Survey_Code, AdultsN$Haul, AdultsN$Functional_Unit, AdultsN$Fishing_Grounds,
                                     AdultsN$fldShotLatDecimalDegrees,AdultsN$fldShotLonDecimalDegrees, 
                                    AdultsN$fldHaulLatDecimalDegrees, AdultsN$fldHaulLonDecimalDegrees),
                            FUN=sum,  na.rm=TRUE)
  names(AdultNumbersMapN) = c("Year", "Survey_Code", "Haul", "Functional_Unit", "Fishing_Grounds",
                             "Lat", "Lon", "LatV2", "LonV2", "NepCount", "PredWt_Kg", "Kg_Hr", "No_Km2", "No_30min")
   AdultNumbersMapN$symbSize <- sqrt( AdultNumbersMapN$No_30min/ pi )
 }else{
   AdultNumbersMapN=data.frame("Year"=maxyear, "Survey_Code"=NA, "Haul"=NA, "Functional_Unit"=NA, "Fishing_Grounds"=NA,
                             "Lat"=55.109, "Lon"=-9.558, "LatV2"=NA, "LonV2"=NA, "NepCount"=NA, "PredWt_Kg"=NA,
                             "Kg_Hr"=NA, "No_Km2"=NA, "No_30min"=NA,"symbSize"=NA)}
# 
# 

# NEP Length/Weight Plot#########
lw<-datN
 lw$NepCount<-round(lw$NepCount,0)
 lw$Weight_g<-(lw$PredWt_Kg/ lw$NepCount)*1000
 
 indLW<-lw%>%uncount(NepCount)
 indLW$FUnit<-as.factor(indLW$Functional_Unit)
 
 
saveRDS(indLW,"updatedData/indLW.RDS")
saveRDS(dat_raised,"updatedData/dat_raised.RDS")
saveRDS(datN,"updatedData/datN.RDS")
saveRDS(AdultNumbersMapN,"updatedData/AdultNumbersMapN.RDS")
saveRDS(JuvNumbersMapN,"updatedData/JuvNumbersMapN.RDS")

```

### Fitting model and saving estimates
```{r coefs,error=F,warning=F,echo=T,message=F,results='hide'}
library(devtools)

#devtools::install_github('droglenc/FSAsim')

library(FSAsim)
library(FSA)
library(magrittr)
library(dplyr)
library(nlstools)
library(tidyverse)
library(broom)
library(lhmixr)
library(tidyverse)
LWA<-LengthWeightAge
#coeff_Length_Age<-function(LWA){
sp_names<-read.csv("Sp_names.csv")
fish<-filter(sp_names,age=="yes")$speciesFAO
fish<-droplevels(fish)
LWA_missingremoved=filter(LWA, !is.na(age) & age>=0  & ICESCODE !="VIIa")
LWA_fish=filter(LWA_missingremoved, fldMainSpeciesCode %in% fish)
LWA_fish<-droplevels(LWA_fish)
#################################################################################################
vbTyp = function(age, Linf, K, t0) Linf*(1-exp(-K*(age-t0)))
#################################################################################################
#################################All data########################################################
#################################################################################################
dfSample = LWA_fish %>%group_by(fldMainSpeciesCode)%>%
do(fitSample = try(nls(length ~ vbTyp(age, Linf, K, t0), data=.,
                       start=vbStarts(length ~ age,data=.))))
coeffs=NULL
for(i in 1:dim(dfSample)[1]){
  if(substring(dfSample$fitSample[[i]][1],1,5)=="Error"){
    coeffs=rbind(coeffs, c(paste(dfSample$fldMainSpeciesCode[[i]]),"All data","None",NA,"No", NA, NA,NA,NA))
  }else{
    coeffs=rbind(coeffs, cbind(paste(dfSample$fldMainSpeciesCode[[i]]),"All data","None",NA,"No",
                               coef(dfSample$fitSample[[i]])[[1]], coef(dfSample$fitSample[[i]])[[2]],
                               coef(dfSample$fitSample[[i]])[[3]],NA))
 }
}
coeffs1=as.data.frame(coeffs)
colnames(coeffs1)=c("Species","Data","Parameter","Year","Cohort","Linf", "K", "t0","Level")


###########################################################################################################
###########################################All sex########################################################
#############################################################################################################
LWA_fishA<-filter(LWA_fish,obs.sex!="unclassified")
LWA_fishA<-droplevels(LWA_fishA)
dfSample = LWA_fishA %>%group_by(fldMainSpeciesCode,obs.sex)%>%
  do(fitSample = try(nls(length ~ vbTyp(age, Linf, K, t0), data=.,
                         start=vbStarts(length ~ age,data=.))))
coeffs=NULL
for(i in 1:dim(dfSample)[1]){
  if(substring(dfSample$fitSample[[i]][1],1,5)=="Error"){
    coeffs=rbind(coeffs, c(paste(dfSample$fldMainSpeciesCode[[i]]),paste("All",dfSample$obs.sex[[i]],"data"),"Sex",NA,"No", NA, NA, NA,paste(dfSample$obs.sex[[i]])))
  }else{
    coeffs=rbind(coeffs, cbind(paste(dfSample$fldMainSpeciesCode[[i]]),paste("All",dfSample$obs.sex[[i]],"data"),"Sex",NA,"No",
                               coef(dfSample$fitSample[[i]])[[1]], coef(dfSample$fitSample[[i]])[[2]],
                               coef(dfSample$fitSample[[i]])[[3]],paste(dfSample$obs.sex[[i]])))
  }
}
coeffs2=as.data.frame(coeffs)
colnames(coeffs2)=c("Species","Data","Parameter","Year","Cohort", "Linf","K", "t0","Level")

###########################################################################################################
###########################################All gear########################################################
###############################################################################################################
LWA_fishGG<-filter(LWA_fish,fldGearDescription!="Griffin 43/53 - New IBTS prototype 2019 full size clean gear")
LWA_fishG<-droplevels(LWA_fishGG)

dfSample = LWA_fishG %>%group_by(fldMainSpeciesCode,fldGearDescription)%>%
  do(fitSample = try(nls(length ~ vbTyp(age, Linf, K, t0), data=.,
                         start=vbStarts(length ~ age,data=.))))
coeffs=NULL
for(i in 1:dim(dfSample)[1]){
  if(substring(dfSample$fitSample[[i]][1],1,5)=="Error"){
    coeffs=rbind(coeffs, c(paste(dfSample$fldMainSpeciesCode[[i]]),paste("All",dfSample$fldGearDescription[[i]],"data"),
                           "Gear", NA,"No", NA, NA,NA,paste(dfSample$fldGearDescription[[i]])))
  }else{
    coeffs=rbind(coeffs, cbind(paste(dfSample$fldMainSpeciesCode[[i]]),paste("All",dfSample$fldGearDescription[[i]],"data"),"Gear",NA,"No",
                               coef(dfSample$fitSample[[i]])[[1]], coef(dfSample$fitSample[[i]])[[2]],
                               coef(dfSample$fitSample[[i]])[[3]],paste(dfSample$fldGearDescription[[i]])))
  }
}
coeffs3=as.data.frame(coeffs)
colnames(coeffs3)=c("Species","Data","Parameter","Year","Cohort", "Linf","K", "t0","Level")

###########################################################################################################
###########################################################################################################
###########################################All division########################################################
###############################################################################################################
dfSample = LWA_fish%>%group_by(fldMainSpeciesCode,ICESCODE)%>%
  do(fitSample = try(nls(length ~ vbTyp(age, Linf, K, t0), data=.,
                         start=vbStarts(length ~ age,data=.))))
coeffs=NULL
for(i in 1:dim(dfSample)[1]){
  if(substring(dfSample$fitSample[[i]][1],1,5)=="Error"){
    coeffs=rbind(coeffs, c(paste(dfSample$fldMainSpeciesCode[[i]]),paste("All",dfSample$ICESCODE[[i]],"data"),
                           "Division", NA,"No", NA, NA,NA,paste(dfSample$ICESCODE[[i]])))
  }else{
    coeffs=rbind(coeffs, cbind(paste(dfSample$fldMainSpeciesCode[[i]]),paste("All",dfSample$ICESCODE[[i]],"data"),
                               "Division",NA,"No",
                               coef(dfSample$fitSample[[i]])[[1]], coef(dfSample$fitSample[[i]])[[2]],
                               coef(dfSample$fitSample[[i]])[[3]],paste(dfSample$ICESCODE[[i]])))
  }
}
coeffs4=as.data.frame(coeffs)
colnames(coeffs4)=c("Species","Data","Parameter","Year","Cohort", "Linf","K", "t0","Level")


###########################################################################################################
###########################################All data by year#################################################
############################################################################################################
dfSample = LWA_fish %>%group_by(fldMainSpeciesCode,Year)%>%
  do(fitSample = try(nls(length ~ vbTyp(age, Linf, K, t0), data=.,
                         start=vbStarts(length ~ age,data=.))))
coeffs=NULL
for(i in 1:dim(dfSample)[1]){
  if(substring(dfSample$fitSample[[i]][1],1,5)=="Error"){
    coeffs=rbind(coeffs, c(paste(dfSample$fldMainSpeciesCode[[i]]),paste(dfSample$Year[[i]],"data"),"None", dfSample$Year[[i]],"No", NA, NA,NA,NA))
  }else{
    coeffs=rbind(coeffs, cbind(paste(dfSample$fldMainSpeciesCode[[i]]),paste(dfSample$Year[[i]],"data"),"None",dfSample$Year[[i]],"No",
                               coef(dfSample$fitSample[[i]])[[1]], coef(dfSample$fitSample[[i]])[[2]],
                               coef(dfSample$fitSample[[i]])[[3]],NA))
  }
}
coeffs5=as.data.frame(coeffs)
colnames(coeffs5)=c("Species","Data","Parameter","Year","Cohort", "Linf","K", "t0","Level")

######################################################################################################
######################################################################################################
###########################################sex by year################################################
######################################################################################################

dfSample = LWA_fishA %>%group_by(fldMainSpeciesCode,obs.sex,Year)%>%
  do(fitSample = try(nls(length ~ vbTyp(age, Linf, K, t0), data=.,
                         start=vbStarts(length ~ age,data=.))))

coeffs=NULL
for(i in 1:dim(dfSample)[1]){
  if(substring(dfSample$fitSample[[i]][1],1,5)=="Error"){
    coeffs=rbind(coeffs, c(paste(dfSample$fldMainSpeciesCode[[i]]),
                           paste(dfSample$Year[[i]],dfSample$obs.sex[[i]],"data"),"Sex",
                           dfSample$Year[[i]],"No", NA, NA, NA,paste(dfSample$obs.sex[[i]])))
  }else{
    coeffs=rbind(coeffs, cbind(paste(dfSample$fldMainSpeciesCode[[i]]),paste(dfSample$Year[[i]],dfSample$obs.sex[[i]],"data"),
                               "Sex",dfSample$Year[[i]],"No",
                               coef(dfSample$fitSample[[i]])[[1]], coef(dfSample$fitSample[[i]])[[2]],
                               coef(dfSample$fitSample[[i]])[[3]],paste(dfSample$obs.sex[[i]])))
  }
}
coeffs6=as.data.frame(coeffs)
colnames(coeffs6)=c("Species","Data","Parameter","Year","Cohort", "Linf","K", "t0","Level")


######################################################################################################
######################################################################################################
###########################################gear by year################################################
###################################################################################################
dfSample = LWA_fishG %>%group_by(fldMainSpeciesCode,fldGearDescription,Year)%>%
  do(fitSample = try(nls(length ~ vbTyp(age, Linf, K, t0), data=.,
                         start=vbStarts(length ~ age,data=.))))

coeffs=NULL
for(i in 1:dim(dfSample)[1]){
  if(substring(dfSample$fitSample[[i]][1],1,5)=="Error"){
    coeffs=rbind(coeffs, c(paste(dfSample$fldMainSpeciesCode[[i]]),paste(dfSample$Year[[i]],dfSample$fldGearDescription[[i]],"data"),
                           "Gear",dfSample$Year[[i]],"No", NA, NA,NA,paste(dfSample$fldGearDescription[[i]])))
  }else{
    coeffs=rbind(coeffs, cbind(paste(dfSample$fldMainSpeciesCode[[i]]),paste(dfSample$Year[[i]],dfSample$fldGearDescription[[i]],"data"),"Gear",
                               dfSample$Year[[i]],"No",
                               coef(dfSample$fitSample[[i]])[[1]], coef(dfSample$fitSample[[i]])[[2]],
                               coef(dfSample$fitSample[[i]])[[3]],paste(dfSample$fldGearDescription[[i]])))
  }
}
coeffs7=as.data.frame(coeffs)
colnames(coeffs7)=c("Species","Data","Parameter","Year","Cohort", "Linf","K", "t0","Level")


######################################################################################################
######################################################################################################
###########################################Div by year################################################
###################################################################################################
dfSample = LWA_fish%>%group_by(fldMainSpeciesCode,ICESCODE,Year)%>%
  do(fitSample = try(nls(length ~ vbTyp(age, Linf, K, t0), data=.,
                         start=vbStarts(length ~ age,data=.))))

coeffs=NULL
for(i in 1:dim(dfSample)[1]){
  if(substring(dfSample$fitSample[[i]][1],1,5)=="Error"){
    coeffs=rbind(coeffs, c(paste(dfSample$fldMainSpeciesCode[[i]]),paste(dfSample$Year[[i]],dfSample$ICESCODE[[i]],"data"),
                           "Division",dfSample$Year[[i]],"No", NA, NA,NA,paste(dfSample$ICESCODE[[i]])))
  }else{
    coeffs=rbind(coeffs, cbind(paste(dfSample$fldMainSpeciesCode[[i]]),paste(dfSample$Year[[i]],dfSample$ICESCODE[[i]],"data")
                               ,"Division",dfSample$Year[[i]],"No",
                               coef(dfSample$fitSample[[i]])[[1]], coef(dfSample$fitSample[[i]])[[2]],
                               coef(dfSample$fitSample[[i]])[[3]],paste(dfSample$ICESCODE[[i]])))
  }
}
coeffs8=as.data.frame(coeffs)
colnames(coeffs8)=c("Species","Data","Parameter","Year","Cohort", "Linf","K", "t0","Level")


########################################################################################
###########################Cohort##############################################################
                              
dfSample = LWA_fish %>%
  filter(Cohort>2002)%>%
  group_by(fldMainSpeciesCode,Cohort)%>%
  do(fitSample = try(nls(length ~ vbTyp(age, Linf, K, t0), data=.,
                         start=vbStarts(length ~ age,data=.))))
coeffs=NULL
for(i in 1:dim(dfSample)[1]){
  if(substring(dfSample$fitSample[[i]][1],1,5)=="Error"){
    coeffs=rbind(coeffs, c(paste(dfSample$fldMainSpeciesCode[[i]]),paste("Cohort",dfSample$Cohort[[i]]),"None", dfSample$Cohort[[i]],"Yes",NA, NA,NA,NA))
  }else{
    coeffs=rbind(coeffs, cbind(paste(dfSample$fldMainSpeciesCode[[i]]),paste("Cohort",dfSample$Cohort[[i]]),"None",dfSample$Cohort[[i]],"Yes",
                               coef(dfSample$fitSample[[i]])[[1]], coef(dfSample$fitSample[[i]])[[2]],
                               coef(dfSample$fitSample[[i]])[[3]],NA))
  }
}
coeffs9=as.data.frame(coeffs)
colnames(coeffs9)=c("Species","Data","Parameter","Year","Cohort", "Linf","K", "t0","Level")


########################################################################################
###########################Cohort by sex#################################################


dfSample = LWA_fishA%>%group_by(fldMainSpeciesCode,Cohort,obs.sex)%>%
  filter(Cohort>2002)%>%
  do(fitSample = try(nls(length ~ vbTyp(age, Linf, K, t0), data=.,
                         start=vbStarts(length ~ age,data=.))))
coeffs=NULL
for(i in 1:dim(dfSample)[1]){
  if(substring(dfSample$fitSample[[i]][1],1,5)=="Error"){
    coeffs=rbind(coeffs, c(paste(dfSample$fldMainSpeciesCode[[i]]),paste("Cohort",dfSample$Cohort[[i]],dfSample$obs.sex[[i]]),
                           "Sex", dfSample$Cohort[[i]],"Yes",NA, NA,NA,paste(dfSample$obs.sex[[i]])))
  }else{
    coeffs=rbind(coeffs, cbind(paste(dfSample$fldMainSpeciesCode[[i]]),paste("Cohort",dfSample$Cohort[[i]],dfSample$obs.sex[[i]]),
                               "Sex",dfSample$Cohort[[i]],"Yes",
                               coef(dfSample$fitSample[[i]])[[1]], coef(dfSample$fitSample[[i]])[[2]],
                               coef(dfSample$fitSample[[i]])[[3]],paste(dfSample$obs.sex[[i]])))
  }
}
coeffs10=as.data.frame(coeffs)
colnames(coeffs10)=c("Species","Data","Parameter","Year","Cohort", "Linf","K", "t0","Level")



########################################################################################
###########################Cohort by gear#################################################


dfSample = LWA_fishG%>%
  filter(Cohort>2002)%>%
  group_by(fldMainSpeciesCode,Cohort,fldGearDescription)%>%
  do(fitSample = try(nls(length ~ vbTyp(age, Linf, K, t0), data=.,
                         start=vbStarts(length ~ age,data=.))))
coeffs=NULL
for(i in 1:dim(dfSample)[1]){
  if(substring(dfSample$fitSample[[i]][1],1,5)=="Error"){
    coeffs=rbind(coeffs, c(paste(dfSample$fldMainSpeciesCode[[i]]),paste("Cohort",dfSample$Cohort[[i]],dfSample$fldGearDescription[[i]]),
                           "Gear", dfSample$Cohort[[i]],"Yes",NA, NA,NA,paste(dfSample$fldGearDescription[[i]])))
  }else{
    coeffs=rbind(coeffs, cbind(paste(dfSample$fldMainSpeciesCode[[i]]),paste("Cohort",dfSample$Cohort[[i]],dfSample$fldGearDescription[[i]]),
                               "Gear",dfSample$Cohort[[i]],"Yes",
                               coef(dfSample$fitSample[[i]])[[1]], coef(dfSample$fitSample[[i]])[[2]],
                               coef(dfSample$fitSample[[i]])[[3]],paste(dfSample$fldGearDescription[[i]])))
  }
}
coeffs11=as.data.frame(coeffs)
colnames(coeffs11)=c("Species","Data","Parameter","Year","Cohort", "Linf","K", "t0","Level")



########################################################################################
###########################Cohort by division#################################################


dfSample = LWA_fish%>%
  filter(Cohort>2002)%>%
  group_by(fldMainSpeciesCode,Cohort,ICESCODE)%>%
  do(fitSample = try(nls(length ~ vbTyp(age, Linf, K, t0), data=.,
                         start=vbStarts(length ~ age,data=.))))
coeffs=NULL
for(i in 1:dim(dfSample)[1]){
  if(substring(dfSample$fitSample[[i]][1],1,5)=="Error"){
    coeffs=rbind(coeffs, c(paste(dfSample$fldMainSpeciesCode[[i]]),
                           paste("Cohort",dfSample$Cohort[[i]],dfSample$ICESCODE[[i]]),
                           "Division", dfSample$Cohort[[i]],"Yes",NA, NA,NA,paste(dfSample$ICESCODE[[i]])))
  }else{
    coeffs=rbind(coeffs, cbind(paste(dfSample$fldMainSpeciesCode[[i]]),paste("Cohort",dfSample$Cohort[[i]],dfSample$ICESCODE[[i]]),
                               "Division",dfSample$Cohort[[i]],"Yes",
                               coef(dfSample$fitSample[[i]])[[1]], coef(dfSample$fitSample[[i]])[[2]],
                               coef(dfSample$fitSample[[i]])[[3]],paste(dfSample$ICESCODE[[i]])))
  }
}
coeffs12=as.data.frame(coeffs)
colnames(coeffs12)=c("Species","Data","Parameter","Year","Cohort", "Linf","K", "t0","Level")



################combined

all_data<-do.call(rbind, lapply(paste0("coeffs", 1:12) , get))

unlink("updatedData/coeff_L_A.csv")
write.csv(all_data,"updatedData/coeff_L_A.csv",row.names = F)

```

